#!/bin/bash
#SBATCH --job-name=align
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=hongbo.liu@ufl.edu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=20gb
#SBATCH --time=160:00:00
pwd; hostname; date
env
module purge
module load bowtie2
bowtie2 -x /ufrc/wang/hongbo.liu/raw_data/totaldna_cdna.index --end-to-end -D 20 -R 3 -N 0 -L 20 -i S,1,0.50  -1 /ufrc/wang/hongbo.liu/raw_data/G101_5G2_1.fq -2 /ufrc/wang/hongbo.liu/raw_data/G101_5G2_2.fq -S G101_5G2.sam

$grep AS:i:0 G101_5G2.sam > G101_5G2.fastq         #提取G101_5G2.sam文件中比对上的序列，然后以fastaq的格式输出。
